apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: violating-clusterrole-infra
  annotations:
    kubeapt.io/uuid: "de80e01b-df84-4253-b44c-6cd8dfad2e7d"
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
