apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: violating-role-rbac-impersonate
  annotations:
    kubeapt.io/uuid: "1cf87d15-93d3-4aaa-8540-c86b819b3e67"
rules:
- apiGroups: [""]
  resources: ["users"]
  verbs: ["impersonate"]
