apiVersion: v1
kind: Pod
metadata:
  name: capabilities-add-containers
  annotations:
    kubeapt.io/uuid: "57487b22-099b-46ad-b669-844e1e392a65"
spec:
  containers:
  - name: main
    image: busybox:1.36
    command:
    - sh
    - -c
    - sleep 3600
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
