apiVersion: v1
kind: Pod
metadata:
  name: run-as-group-ephemeralcontainers
  annotations:
    kubeapt.io/uuid: "fb6e2c02-8653-4d6a-8f60-38512cc54daf"
spec:
  containers:
  - name: main
    image: busybox:1.36
    command:
    - sh
    - -c
    - sleep 3600
---
# Command: kubectl debug -n policy-test run-as-group-ephemeralcontainers -it --image=busybox:1.36 --custom=policies/run-as-group/ephemeralcontainers/deny-kubectl-debug-custom.yaml
