apiVersion: v1
kind: ServiceAccount
metadata:
  name: violating-no-token-secrets
  annotations:
    kubeapt.io/uuid: "4274c4b5-6f75-45aa-837b-b0641f9a7660"
automountServiceAccountToken: false
secrets:
- name: legacy-token
