apiVersion: v1
kind: Pod
metadata:
  name: selinux-user-ephemeralcontainers
  annotations:
    kubeapt.io/uuid: "4598e7df-4c5e-4ee2-a0b5-9ce4179a89fc"
spec:
  containers:
  - name: main
    image: busybox:1.36
    command:
    - sh
    - -c
    - sleep 3600
---
# Command: kubectl debug -n policy-test selinux-user-ephemeralcontainers -it --image=busybox:1.36 --custom=policies/selinux-user/ephemeralcontainers/deny-kubectl-debug-custom.yaml
