apiVersion: v1
kind: ConfigMap
metadata:
  name: violating-no-executable-code
  annotations:
    kubeapt.io/uuid: "2d9872e4-6538-497b-b9f1-64479e562fcd"
immutable: true
data:
  run.sh: |
    #!/bin/bash
    echo "bad"
