apiVersion: v1
kind: Service
metadata:
  name: violating-external-ips
  annotations:
    kubeapt.io/uuid: "67c6d14c-e374-4cfc-87aa-94f214f1e104"
spec:
  type: ClusterIP
  selector:
    app: test
  externalIPs:
  - 203.0.113.10
  ports:
  - name: web
    port: 80
    targetPort: 80
