apiVersion: v1
kind: Pod
metadata:
  name: violating-dns-policy
  annotations:
    kubeapt.io/uuid: "cfbd76cd-b41a-4146-a2dd-1d08e125f7a4"
spec:
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: main
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
