apiVersion: v1
kind: Node
metadata:
  name: violating-control-plane
  annotations:
    kubeapt.io/uuid: "b0cfc6a8-e466-4436-b2a8-a7d94fbab61a"
  labels:
    node-role.kubernetes.io/control-plane: ""
spec:
  taints:
  - key: node-role.kubernetes.io/control-plane
    effect: PreferNoSchedule
