apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: violating-storageclass-encryption-ceph-rbd
  annotations:
    kubeapt.io/uuid: "f9881fc5-db3d-4cd5-9788-f6529f0f853e"
provisioner: rbd.csi.ceph.com
parameters:
  pool: rbd
